### PR TITLE
TS-393: Search Result API

### PR DESCRIPTION
**Pull request by GadoliniumPotassium**
Search results page now returns results. The lack of profile pics and company logos makes it look jarring. In addition, the is follower method does not seem to be working but I will take help on that.

### CODE REVIEW

**Comment by GadoliniumPotassium** [comment]
Tests are failing because for some reason the followers aren't visible because there are no followers being pulled and in addition for some reason the method is not returning true when you do follow a person!

**Comment by AlyaNaseer** [comment]
Yeah it's strange, for some reason it isn't splitting the search results based on people you do follow and people you don't. John Lee (@zhongli) should be under Following instead of People. Strange...
image

Also why are there so many "John Doe"s and why don't they have usernames?

**Comment by GadoliniumPotassium** [comment]
> 

I am using the isFollowing method to validate and I'm not sure why it isn't working from the front end services.

**Comment by Ming424** [comment]
image
Maybe remove the isFollow and only display user without follow stuff

**Comment by Ming424** [comment]
image: {
      type: String,
      default: require('../../assets/default_user.png')
    },
also use props for user with no profile pic

**Review by Ming424 — APPROVED** [review]

**Review by AlyaNaseer — APPROVED** [review]
LGTM, if we have time, would be nice to add a placeholder for the company logo and make all the buttons function

**Pull request merged**
