### PR TITLE
[TS-320] Implement the updates Followers/Following pages

### PR DESCRIPTION
**Pull request by Ming424**
- reuse UserBlock with new added parameter request to transform it into a request [confirm, delete]
- fix notification UI
- improve overall UI

- Following
image
- Follower-1
image
- Follower-2
image

### CODE REVIEW

**Review by itsShaVawn — CHANGES_REQUESTED** [review]
image
We aren't using this anymore for notification, just remove the code for it

**Comment by GadoliniumPotassium** [comment]
> image We aren't using this anymore for notification, just remove the code for it

If you're going to do that don't forget to remove the tests for it

**Comment by Ming424** [comment]
> 

Its solve

**Comment by Ming424** [comment]
> 

Thanks for remainder, its removed!

**Review by itsShaVawn — APPROVED** [review]

**Review by tungleu — APPROVED** [review]

**Pull request merged**
