### PR TITLE
Ts 452: Testing to 80%

### PR DESCRIPTION
**Pull request by GadoliniumPotassium**
image

Here are the tests

### CODE REVIEW

**Comment by Ming424** [comment]
Need to check how to avoid duplicate check inside E2E for sonar

**Comment by GadoliniumPotassium** [comment]
The test is passing locally but failing in the CI and I'm so confused as to why

**Comment by GadoliniumPotassium** [comment]
image
Here is the test passing locally but failing in the CI

**Comment by Ming424** [comment]
I think to give a little bit more wait time for loading the pie chart

**Comment by GadoliniumPotassium** [comment]
> I think to give a little bit more wait time for loading the pie chart

I'm already giving it 5 seconds before it starts looking how much time could it need!

**Review by tungleu — APPROVED** [review]

**Review by Ming424 — APPROVED** [review]

**Pull request merged**
