### PR TITLE
[TS-479] Update Position table 

### PR DESCRIPTION
**Pull request by tungleu**
As per stakeholders' request: 

image

Before : 
image

After: 
image

All data are legit

### CODE REVIEW

**Review by Ming424 — DISMISSED** [review]
lgtm

**Review by bowe99 — CHANGES_REQUESTED** [review]
Can you have it so the cost basis and the market value are fixed to 2 decimal places all the time

**Review by bowe99 — COMMENTED** [review]
Also if you can fix the P/L while you are at it I think they should be multiplied by 100 I don't think the percentage value is correct

**Comment by tungleu** [comment]
> Can you have it so the cost basis and the market value are fixed to 2 decimal places all the time

Done :)

**Comment by tungleu** [comment]
> Also if you can fix the P/L while you are at it I think they should be multiplied by 100 I don't think the percentage value is correct

yea you are right!

**Review by bowe99 — APPROVED** [review]

**Review by Ming424 — APPROVED** [review]
lgtm

**Pull request merged**
