### PR TITLE
[REFACTOR][TS-301] Refactoring ready

### PR DESCRIPTION
**Pull request by Ming424**
Followed Vue.js coding style https://vuejs.org/v2/style-guide/
And this article https://medium.com/teamarimac/refactoring-vue-js-code-7725d1720722
Draft for structure (Miro board): https://miro.com/welcomeonboard/bll0SG13OW5yRHdhUEdHOG1BaGJxa3VGajYxaXhwVGtLMVlYQWcwTklTTXI1a1JpS2luYlA1OGdQMnIxajM5MnwzMDc0NDU3MzUzNDcwMjMyMTY2?invite_link_id=693460591029
+ Implement mixing for common function (separation of concern)
+ Refactor data type for missing props
+ Removed related label component (also E2E testing)
+ Fix sign up page autofill causes overlapping text
+ Fix visuals
+ Create hook for manage credential (src/hooks/useCredential.js) and update methods that involve with
+ Remove style tags
+ Remove no-used tags
+ Add files for service hooks

Next step:
I will create a PR only for indentation, otherwise there will be too much file for review.

### CODE REVIEW

**Comment by Ming424** [comment]
src/hooks:
-Hooks for api calling, several empty files for future implementation.
cypress/integration/E2E_test:
-Remove tests relate to label
src/components:
-Add call for hooks
-Fix props type
-Remove labels
-[Important!] Few change (big chunk of red and green) is cause to indentation, you can skip them to review faster.

**Comment by GadoliniumPotassium** [comment]
Everything looks good but I am going to wait for others to validate before I approve. In addition, I would suggest removing the commented out code. It can be retrieved from the source control tree if needed later on.

**Comment by Ming424** [comment]
> Everything looks good but I am going to wait for others to validate before I approve. In addition, I would suggest removing the commented out code. It can be retrieved from the source control tree if needed later on.

Comments removed 👌

**Comment by AlyaNaseer** [comment]
I'd rename your last few commits to something more clear than "Update XX" since we don't know what that means. In fact, I'm pretty sure that removing comments is considered code clean-up, so maybe it's also refactoring? If so, I'd add [REFACTOR] at the beginning as well.

**Review by AlyaNaseer — CHANGES_REQUESTED** [review]
The code itself is approved but I'd rename your last few commits to something more clear than "Update XX" since we don't know what that means. In fact, I'm pretty sure that removing comments is considered code clean-up, so maybe it's also refactoring? If so, I'd add [REFACTOR] at the beginning as well.

**Comment by Ming424** [comment]
> 

Commit renamed 👌

**Comment by Ming424** [comment]
Updated from Main branch

**Review by AlyaNaseer — DISMISSED** [review]
LGTM! Great work!

**Comment by GadoliniumPotassium** [comment]
27 tests are now failing, I tried re running the tests but I always achieve the same result. I suggest you look into it.

**Review by GadoliniumPotassium — APPROVED** [review]
LGTM. Good job! If someone finds something amuck make sure to give a heads up!

**Review by AlyaNaseer — APPROVED** [review]

**Pull request merged**
