### PR TITLE
[TS-468] Added message persistence + create conversation

### PR DESCRIPTION
**Pull request by tungleu**
Things included in this PR: 
- **Search for user to create conversation**
- **Create a conversation on selected user** 
- **Working persistent chat system**

Not included in this PR: 
- Group message

### CODE REVIEW

**Review by rileykc98 — APPROVED** [review]
Looks good. Just be sure to follow the naming convention for commits and include the issue tag in front of the description.

**Review by AlyaNaseer — CHANGES_REQUESTED** [review]
Awesome work! The only thing I noticed is that when you create a new conversation with a user, the conversation isn't highlighted on the left side panel. Do you think you can look into that? I think it's because the highlight is when you select/click an item, but since you're creating a new one, it doesn't force the selection/click.

**Comment by tungleu** [comment]
> Awesome work!
> 
> There are a few small changes I'd suggest.
> 
> 1. When you create a new conversation with a user, the conversation isn't highlighted on the left side panel. Do you think you can look into that? I think it's because the highlight is when you select/click an item, but since you're creating a new one, it doesn't force the selection/click.
> 2. You can actually create more than once conversation with the same person, is there a way you could prevent that from happening? Like checking if the username already is associated to a conversation?
> 3. Could you add a :loading="isLoading" (check other search bars) to the search bar so the user knows something is happening?
> 4. Can we make search by name too? Or just username?
> 5. Is there a way to correct this difference in height (last message exists vs no last message?):

1. I attempted many different approaches but still haven't figured out how to force click correctly :( We can file a bug then figure it out later. 
2. Added a condition to prevent this happens, if the username is already there then it will redirect to that existing conversation 
image

3. Added 
image

4. For now just username, once we enhance the search endpoint in the backend I will change it 👍 
5. Fixed: 
>    image

**Review by AlyaNaseer — APPROVED** [review]

**Comment by AlyaNaseer** [comment]
The loading doesn't quite work but it's not specific to your PR, there's something wrong with the search in the navbar as well. Just writing a note here so we remember that it is also problematic for this PR

**Review by GadoliniumPotassium — APPROVED** [review]

**Pull request merged**
