### PR TITLE
[REFACTOR][TS-413]

### PR DESCRIPTION
**Pull request by itsShaVawn**
This PR contains the configuration for ESLint based on the standard coding rules and practices for Javascript and VueJS.
The linter was then run on each file and issues were fixed.

### CODE REVIEW

**Comment by AlyaNaseer** [comment]
Looks good to me (though I didn't check every file since I assumed it was just linting changes) but you've got some Conflicting files, so I'll approve afterwards, so it doesn't automatically dismiss my review.

**Review by GadoliniumPotassium — COMMENTED** [review]
It looks good to me, but I will approve when the merge conflicts are dealt with. Good job!

**Review by GadoliniumPotassium — APPROVED** [review]
BIG APPROVAL ON MY PART

**Comment by AlyaNaseer** [comment]
Shouldn't we deal with the code smell before merging?

**Comment by itsShaVawn** [comment]
The code smell is this 
image
where in a previous PR i explained that there has been no fix/alternative for over 5 years for this function

**Review by AlyaNaseer — APPROVED** [review]
We should deal with the code smell first

**Pull request merged**
