### PR TITLE
[TS-210] Integrate blocking unwanted users

### PR DESCRIPTION
**Pull request by bowe99**
Integrate blocking unwanted user

https://user-images.githubusercontent.com/50396173/160527897-3c0b53b4-ec26-479e-91e2-20675e75000a.mp4

s

### CODE REVIEW

**Comment by itsShaVawn** [comment]
I noticed this strange behavior with the search bar, but I will still approve because it's not really related to this PR
https://user-images.githubusercontent.com/49250036/160530190-7c351b53-5840-49cf-8e63-bd3986984e42.mp4

**Review by itsShaVawn — DISMISSED** [review]

**Comment by itsShaVawn** [comment]
You also have this code smell 
image

**Comment by AlyaNaseer** [comment]
Shouldn't blocking a user mean you yourself don't see their content anymore either? We either should show that or a snackbar that tells the user that they blocked that user, right now we don't have any visual feedback

**Comment by bowe99** [comment]
@AlyaNaseer No when you block someone on Instagram or Facebook is so that the user you are blocking can no longer view your profile or stalk you in many cases. I just tried on Insta I can still see the persons content if they are blocked but I can change the Profile widget to show a button to unblock instead when viewing someone you blocked

**Comment by AlyaNaseer** [comment]
> @AlyaNaseer No when you block someone on Instagram or Facebook is so that the user you are blocking can no longer view your profile or stalk you in many cases. I just tried on Insta I can still see the persons content if they are blocked but I can change the Profile widget to show a button to unblock instead when viewing someone you blocked

Perfect, and yeah I'd add some sort of visual feedback, be it an unblock button or a snackbar. Probably unblock button would be best

**Comment by itsShaVawn** [comment]
> > @AlyaNaseer No when you block someone on Instagram or Facebook is so that the user you are blocking can no longer view your profile or stalk you in many cases. I just tried on Insta I can still see the persons content if they are blocked but I can change the Profile widget to show a button to unblock instead when viewing someone you blocked
> 
> Perfect, and yeah I'd add some sort of visual feedback, be it an unblock button or a snackbar. Probably unblock button would be best

unblock is just clicking the block button again

**Comment by bowe99** [comment]
> > > @AlyaNaseer No when you block someone on Instagram or Facebook is so that the user you are blocking can no longer view your profile or stalk you in many cases. I just tried on Insta I can still see the persons content if they are blocked but I can change the Profile widget to show a button to unblock instead when viewing someone you blocked
> > 
> > 
> > Perfect, and yeah I'd add some sort of visual feedback, be it an unblock button or a snackbar. Probably unblock button would be best
> 
> unblock is just clicking the block button again

Should we have some sort of UI indication that the user is blocked for the person doing the blocking

**Comment by itsShaVawn** [comment]
> > > > @AlyaNaseer No when you block someone on Instagram or Facebook is so that the user you are blocking can no longer view your profile or stalk you in many cases. I just tried on Insta I can still see the persons content if they are blocked but I can change the Profile widget to show a button to unblock instead when viewing someone you blocked
> > > 
> > > 
> > > Perfect, and yeah I'd add some sort of visual feedback, be it an unblock button or a snackbar. Probably unblock button would be best
> > 
> > 
> > unblock is just clicking the block button again
> 
> Should we have some sort of UI indication that the user is blocked for the person doing the blocking

isn't there already a snackbar?

**Comment by AlyaNaseer** [comment]
> > > > > @AlyaNaseer No when you block someone on Instagram or Facebook is so that the user you are blocking can no longer view your profile or stalk you in many cases. I just tried on Insta I can still see the persons content if they are blocked but I can change the Profile widget to show a button to unblock instead when viewing someone you blocked
> > > > 
> > > > 
> > > > Perfect, and yeah I'd add some sort of visual feedback, be it an unblock button or a snackbar. Probably unblock button would be best
> > > 
> > > 
> > > unblock is just clicking the block button again
> > 
> > 
> > Should we have some sort of UI indication that the user is blocked for the person doing the blocking
> 
> isn't there already a snackbar?

I didn't see one...

**Review by GadoliniumPotassium — APPROVED** [review]
LGTM

**Pull request merged**
