### PR TITLE
[TS-478][TS-487] integrated cards and recent trades on main dashboard

### PR DESCRIPTION
**Pull request by tungleu**
Added daily change, portfolio age, monthly P/L
image

Not sure if monthly P/L is correct tho (16% is fake), might need to ask the stakeholders.

### CODE REVIEW

**Comment by itsShaVawn** [comment]
you have 3 code smells

**Comment by AlyaNaseer** [comment]
You've got some failing tests :(

**Comment by itsShaVawn** [comment]
you still have code smells

**Comment by tungleu** [comment]
> you still have code smells

image

**Review by Ming424 — COMMENTED** [review]
Looks good just E2E left

**Review by GadoliniumPotassium — APPROVED** [review]

**Pull request merged**
