### PR TITLE
[TS-495] added no linked account indication 

### PR DESCRIPTION
**Pull request by tungleu**
https://user-images.githubusercontent.com/30036024/161404297-118b483a-fe71-4675-95db-8120f6eec779.mp4

Before: 
image
After: 
image

Other Dashboard 
Before: 
image
After: 
image

### CODE REVIEW

**Review by Ming424 — APPROVED** [review]
looks good, I need to made few change to the e2e after this is merged

**Review by AlyaNaseer — APPROVED** [review]
Awesome work! You've got conflicting files though, ping me so I can reapprove after you merge main (if it dismisses my review)

**Comment by GadoliniumPotassium** [comment]
Fix your conflict and I'll approve

**Comment by tungleu** [comment]
It's already merged lol

**Pull request closed without merging**
