### PR TITLE
[TS-275]: Single Post page functioning & [TS-298]

### PR DESCRIPTION
**Pull request by itsShaVawn**
**Comment section** is hard coded because we are not focusing on this. It's just for **visual & demonstration purposes** i.e not optimal.
Link for the URL can be copied to clipboard by clicking on the link button -> snackbar indicator and you can CTRL-V in your browser.
Clicking on specific posts from the news feed leads to the correct post page.

### CODE REVIEW

**Comment by itsShaVawn** [comment]
The code smell is because apparently this `execCommand()` is depreciated but from internet research, there is no official alternative and there hasn't been any for 5 years

**Comment by itsShaVawn** [comment]
Duplication will be gone once the backend integration is done

**Comment by itsShaVawn** [comment]
image

**Review by bowe99 — APPROVED** [review]

**Review by GadoliniumPotassium — APPROVED** [review]
its perfect!

**Pull request merged**
