### PR TITLE
[TS-333] Privacy & Security Preferences

### PR DESCRIPTION
**Pull request by itsShaVawn**
Contains the page for the privacy settings in preferences.

image
image

### CODE REVIEW

**Review by AlyaNaseer — COMMENTED** [review]
Looks good to me! Little nit:

image

I find having the text of the location info that big looks a little weird, especially right beneath really small text.

**Comment by AlyaNaseer** [comment]
Also, we'll need to make a task for doing the Cypress tests of these pages

**Comment by itsShaVawn** [comment]
> Looks good to me! Little nit:
> 
> image
> 
> I find having the text of the location info that big looks a little weird, especially right beneath really small text.

image
 is this better?

**Review by tungleu — APPROVED** [review]

**Comment by AlyaNaseer** [comment]
> > Looks good to me! Little nit:
> > image
> > I find having the text of the location info that big looks a little weird, especially right beneath really small text.
> 
> image is this better?

Yes perfect!

**Review by AlyaNaseer — APPROVED** [review]

**Pull request merged**
