### PR TITLE
[TS-437] & [TS-399] Block, favorite & profile card changes

### PR DESCRIPTION
**Pull request by itsShaVawn**
Navigate to this page `http://localhost:8081/dashboard/6204a777f82a1fb5c9f80a1f`

Changes:

1. Added a block button
2. Added a favorite button
3. Removed the bio
4. Re-worked the profile card

_*The profile card on screen sizes < 400px is kind of weird. Bug for later._

After:
image
Before:
image

### CODE REVIEW

**Review by AlyaNaseer — COMMENTED** [review]
When I navigated to the link for the first time, I see the header "User doesn't exist" for quite a bit, and it flashes every time you refresh.

I noticed that on my screen, the pie chart component gets cut off (with no option to horizontal scroll). We should create a bug for it:

image

**Review by AlyaNaseer — CHANGES_REQUESTED** [review]
I think we should address the "User doesn't exist" message that stays there for a while the first time you run the code, and the fact that it flashes every time you refresh the page

**Comment by AlyaNaseer** [comment]
Small discussion on Discord: 
image

**Comment by itsShaVawn** [comment]
> I think we should address the "User doesn't exist" message that stays there for a while the first time you run the code, and the fact that it flashes every time you refresh the page

This is a good idea, let's make it a separate bug

**Review by AlyaNaseer — APPROVED** [review]
Will be addressing the points brought up in this PR in a separate bug

**Comment by itsShaVawn** [comment]
4 states:

Getting information/waiting:
image

User does not exist:
image

User is blocked:
image

Success:
image

**Review by tungleu — APPROVED** [review]

**Comment by tungleu** [comment]
well done :) I personally would prefer the button has the same color as the other buttons

**Pull request merged**
