### PR TITLE
[TS-151] Added sign up test

### PR DESCRIPTION
**Pull request by AlyaNaseer**
Added the edge case tests (but not the successful case as this potentially requires stubbing, and will be looked at after the holiday break, will also need to stub testing with existing email):
- empty fields should fail
- invalid email format should fail
- invalid password (less than 8 characters) should fail
- mismatching passwords should fail

### CODE REVIEW

**Comment by rileykc98** [comment]
Looks like sonarcloud wants you to do some refactoring. Maybe make a function that takes the email, password, names etc. as parameters and enters them into the boxes, then just do the respective assertions in the main method body.

**Comment by AlyaNaseer** [comment]
> Looks like sonarcloud wants you to do some refactoring. Maybe make a function that takes the email, password, names etc. as parameters and enters them into the boxes, then just do the respective assertions in the main method body.

Yeah working that now!

**Comment by AlyaNaseer** [comment]
@rileykc98 Reworked it to eliminate code duplication :)

**Review by rileykc98 — APPROVED** [review]
Great! Nice job refactoring the code duplication.

**Review by tungleu — APPROVED** [review]
tests passed on local and CI, great work!

**Pull request merged**
