### PR TITLE
[TS-53] Implement profile accessibility in private account

### PR DESCRIPTION
**Pull request by bowe99**
https://user-images.githubusercontent.com/50396173/160298011-deb45705-9b38-4ac7-aa28-b2c595aa320c.mp4

Demo of profile accessibility with private users

### CODE REVIEW

**Review by Ming424 — APPROVED** [review]
Looks good, I will made a slight change from my PR after I merge it. For private account, when user send a follow request, button will be change to [Sent Request].

**Comment by bowe99** [comment]
Yeah that sounds good you may also want to remove the bypassPrivate from the follow request in your branch

**Comment by Ming424** [comment]
> 

I will use that once the private account owner approved the request, good to have in advanced!

**Review by AlyaNaseer — DISMISSED** [review]
Awesome work Kev!

**Review by tungleu — APPROVED** [review]
Noice 🦘

**Review by AlyaNaseer — APPROVED** [review]

**Pull request merged**
